### ISSUE TITLE
fails on Fedora 22, trying to run under python3

### ISSUE THREAD

**Issue by cuviper** [tromey/gdb-gui#29]
It appears that GDB on Fedora 22 has transistioned to python3.  I get this error on startup:

```
Traceback (most recent call last):
  File "/home/jistone/src/gdb-gui/gdb-gui.py", line 3, in <module>
    import gui.commands
  File "/home/jistone/src/gdb-gui/gui/__init__.py", line 21, in <module>
    import gui.commands
  File "/home/jistone/src/gdb-gui/gui/commands.py", line 68
    print "Ambiguous linespec, only showing first result"
                                                        ^
SyntaxError: Missing parentheses in call to 'print'
```

That's a very obvious py2-ism, but I have no idea how extensively things need to be changed.  The result from `2to3` looks pretty straightforward though.

**Comment by cuviper** [comment]
Thanks!  Looks like it's working fine.
