### ISSUE TITLE
exception when interrupting

### ISSUE THREAD

**Issue by tromey** [tromey/gdb-gui#36]
got an exception

```
Traceback (most recent call last):
  File "/home/tromey/gdb/gdb-gui/gui/startup.py", line 85, in ensure_gdb_thread
    return func(*args, **kwargs)
  File "/home/tromey/gdb/gdb-gui/gui/updatewindow.py", line 55, in _on_event
    self.on_event()
  File "/home/tromey/gdb/gdb-gui/gui/startup.py", line 85, in ensure_gdb_thread
    return func(*args, **kwargs)
  File "/home/tromey/gdb/gdb-gui/gui/stack.py", line 99, in on_event
    data = list(map(format_frame, frame_iter))
  File "/home/tromey/gdb/gdb-gui/gui/stack.py", line 33, in format_frame
    result["filename"] = frame.filename()
  File "/usr/local/stow/my-gdb/share/gdb/python/gdb/FrameDecorator.py", line 143, in filename
    return gdb.solib_name(pc)
OverflowError: int too big to convert
```

**Comment by tromey** [comment]
This turned out to be a gdb bug.
See https://sourceware.org/bugzilla/show_bug.cgi?id=18984
